---
Name: UpgradeImport
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ImportSiteConfigExtension
#ADD THIS !!!! to project Config
#SilverStripe\ORM\DataObject:
#  extensions:
#    - ImportDataExtension
#add to project config If Module exists
#FAQ\DataObjects\FAQ:
#  extensions:
#    - FAQImportExtension
#Reference\DataObjects\Reference:
#  extensions:
#    - ReferenceImportExtension
